### ISSUE TITLE
Bukget filter by 0-9 A...Z is multiplying

### ISSUE THREAD

**Issue by GoldenIrony** [XereoNet/SpaceBukkit#42] opened 2011-12-23 18:28 UTC
Well i can't explain this bug good so you get an Image, also it is not so important. 
Well when i try to click i he gives me a new row of A-9 A..Z and again and again. 

Found in Spacebukkit v1.02

http://imageshack.us/photo/my-images/196/erroruq.png/

**Comment by Antariano** [comment] 2011-12-23 19:20
Thanks for your notification, I'm on it

**Comment by JamyDev** [comment] 2011-12-26 11:48
BukGet is down atm, I'll fix it once it's back up; This could be after 1.04..
Moved this for 1.05

**Comment by JamyDev** [comment] 2011-12-30 16:38
Moving to 1.05 due to BukGet downtime

**Comment by JamyDev** [comment] 2011-12-30 18:41
Can't seem to reproduce the error anymore; What browser did you use?

**Closed as completed by JamyDev** 2011-12-30 18:41 UTC
Labels: Panel
